print(39*'-')
print('|        Roberto                      |')
print('|'+ (37*' ')+'|')
print('|        5786                         |')
print('|'+ (37*' ')+'|')
print('|        UNIFEI                       |')
print(39*'-')