print(39*'-')
print('|x = 35                               |')
print('|'+ (37*' ')+'|')
print('|                x = 35               |')
print('|'+ (37*' ')+'|')
print('|                               x = 35|')
print(39*'-')